#!/usr/bin/env python3
"""make bundle -> dist/tracker.py : re-inline the aitracker package + web assets
into one standalone, zero-dependency file (the 'copy one file and run it' build)."""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, "aitracker")

# dependency order
ORDER = [
    "config.py", "util.py", "store.py", "overview.py",
    "providers/base.py", "providers/claude.py", "providers/auggie.py",
    "providers/augment_ext.py", "providers/opencode.py",
    "registry.py", "server.py", "cli.py",
]

HEADER = '''#!/usr/bin/env python3
"""AI Session Tracker — standalone single-file build (generated by `make bundle`).
Edit the sources in aitracker/ + web/, not this file. Zero dependencies; stdlib only."""
import datetime, difflib, glob, json, os, re, subprocess, sys, time, webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

__version__ = "%s"
'''


def strip_module(src):
    lines = src.splitlines()
    skip_indices = set()

    # identify all import lines (including multi-line continuations) to drop
    i = 0
    while i < len(lines):
        line = lines[i]
        if re.match(r'^(import |from )', line):
            skip_indices.add(i)
            # if import spans multiple lines (has unclosed paren), skip continuation lines too
            if '(' in line and ')' not in line:
                i += 1
                while i < len(lines):
                    skip_indices.add(i)
                    if ')' in lines[i]:
                        break
                    i += 1
        i += 1

    out = [line for i, line in enumerate(lines) if i not in skip_indices]
    body = "\n".join(out)
    body = re.sub(r'(?<![\w.])config\.', '', body)   # single namespace — config.X -> X
    return body.strip("\n")


def inlined_page():
    web = os.path.join(PKG, "web")
    html = open(os.path.join(web, "index.html")).read()
    css = open(os.path.join(web, "app.css")).read()
    js = open(os.path.join(web, "app.js")).read()
    page = html.replace("__CSS__", css).replace("__JS__", js)
    assert '"""' not in page, "page contains triple-quotes; bundler needs a different quoting"
    return 'PAGE = r"""' + page + '"""\n'


def main():
    version = re.search(r'__version__\s*=\s*"([^"]+)"',
                        open(os.path.join(PKG, "__init__.py")).read()).group(1)
    parts = [HEADER % version]
    for rel in ORDER:
        body = strip_module(open(os.path.join(PKG, rel)).read())
        if rel == "server.py":
            body = body.replace("build_page()", "PAGE")           # inline page
            # remove optional module loading (terminal modules are inlined, not importable as separate modules)
            body = re.sub(
                r'for _m in \("term_launch", "term_run", "term_vt"\):[\s\S]*?raise',
                '',
                body
            )
            parts.append(inlined_page())
        if rel == "cli.py":
            # the bundle has no test suite; make --selfcheck point at the repo
            body = body.replace(
                "        _selfcheck()\n        return",
                "        print(\"Bundled build — run 'make check' in the repo for the self-check.\")\n        return")
            body = re.sub(r'\ndef _selfcheck\(\):.*?(?=\ndef main\()', '\n', body, flags=re.S)
        parts.append("# --- %s ---\n%s" % (rel, body))
    parts.append('\nif __name__ == "__main__":\n    main()\n')

    os.makedirs(os.path.join(ROOT, "dist"), exist_ok=True)
    out = os.path.join(ROOT, "dist", "tracker.py")
    open(out, "w").write("\n\n".join(parts))
    print("wrote", os.path.relpath(out, ROOT), "(%d KB)" % (os.path.getsize(out) // 1024))


if __name__ == "__main__":
    main()
