#!/usr/bin/env python3
"""make bundle -> dist/tracker.py : re-inline the aitracker package + web assets
into one standalone, zero-dependency file (the 'copy one file and run it' build)."""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, "aitracker")

# dependency order
ORDER = [
    "config.py", "util.py", "store.py", "overview.py",
    "providers/base.py", "providers/claude.py", "providers/auggie.py",
    "providers/augment_ext.py",
    "registry.py", "server.py", "cli.py",
]

HEADER = '''#!/usr/bin/env python3
"""AI Session Tracker — standalone single-file build (generated by `make bundle`).
Edit the sources in aitracker/ + web/, not this file. Zero dependencies; stdlib only."""
import datetime, difflib, glob, json, os, re, subprocess, sys, time, webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

__version__ = "%s"
'''


def strip_module(src):
    out = []
    for line in src.splitlines():
        if re.match(r'^(import |from )', line):      # drop top-level imports (re-added in HEADER)
            continue
        out.append(line)
    body = "\n".join(out)
    body = re.sub(r'(?<![\w.])config\.', '', body)   # single namespace — config.X -> X
    return body.strip("\n")


def inlined_page():
    web = os.path.join(PKG, "web")
    html = open(os.path.join(web, "index.html")).read()
    css = open(os.path.join(web, "app.css")).read()
    js = open(os.path.join(web, "app.js")).read()
    page = html.replace("__CSS__", css).replace("__JS__", js)
    assert '"""' not in page, "page contains triple-quotes; bundler needs a different quoting"
    return 'PAGE = r"""' + page + '"""\n'


def main():
    version = re.search(r'__version__\s*=\s*"([^"]+)"',
                        open(os.path.join(PKG, "__init__.py")).read()).group(1)
    parts = [HEADER % version]
    for rel in ORDER:
        body = strip_module(open(os.path.join(PKG, rel)).read())
        if rel == "server.py":
            body = body.replace("build_page()", "PAGE")           # inline page
            # The terminal-tier loader below relies on `__import__("%s.%s" % (__package__, _m))`
            # to optionally pull in term_launch/term_run/term_vt as real PACKAGE SUBMODULES --
            # meaningless once this file is flattened into one standalone script. Worse than
            # meaningless: run standalone, __package__ is None (not ""), so "%s.%s" % (None, _m)
            # produces "None.term_vt", __import__ raises ModuleNotFoundError(name="None") --
            # e.name ("None") != the expected "None.term_vt" -- and the loop's own `raise` fires,
            # crashing --version/--help/--selfcheck alike. The terminal tiers themselves are not
            # bundled (they cross-reference each other and server/store via bare `module.attr`
            # access that only resolves inside the real package -- flattening that cleanly is a
            # separate, larger effort); replace the loop with a no-op so the standalone build
            # simply ships without the terminal feature, matching what already silently happened
            # before this fix (the loop always no-op'd for a genuinely-absent module) instead of
            # crashing on it.
            body = re.sub(
                r'for _m in \("term_launch", "term_run", "term_vt"\):\n'
                r'    try:\n'
                r'        __import__\("%s\.%s" % \(__package__, _m\)\)\n'
                r'    except ModuleNotFoundError as e:\n'
                r'        if e\.name != "%s\.%s" % \(__package__, _m\):\n'
                r'            raise',
                '# terminal-tier loader removed for the standalone bundle -- see bundle.py',
                body)
            assert "__package__" not in body, \
                "terminal-tier loader text changed upstream; update the regex in bundle.py"
            parts.append(inlined_page())
        if rel == "cli.py":
            # the bundle has no test suite; make --selfcheck point at the repo
            body = body.replace(
                "        _selfcheck()\n        return",
                "        print(\"Bundled build — run 'make check' in the repo for the self-check.\")\n        return")
            body = re.sub(r'\ndef _selfcheck\(\):.*?(?=\ndef main\()', '\n', body, flags=re.S)
        parts.append("# --- %s ---\n%s" % (rel, body))
    parts.append('\nif __name__ == "__main__":\n    main()\n')

    os.makedirs(os.path.join(ROOT, "dist"), exist_ok=True)
    out = os.path.join(ROOT, "dist", "tracker.py")
    open(out, "w").write("\n\n".join(parts))
    print("wrote", os.path.relpath(out, ROOT), "(%d KB)" % (os.path.getsize(out) // 1024))


if __name__ == "__main__":
    main()
